FROM docker.caste.dev/sardina:latest

# https://forums.docker.com/t/how-to-run-a-cron-job-inside-a-container-alpine/7759/7
RUN echo "*/5 * * * * python -u /sardina/main.py --ping" > /etc/crontabs/root
CMD crond -l 0 -f

# build with:
#   docker build -f Dockerfile.cron -t sardina-cron .
# run with:
#   docker run --rm -itd sardina-cron
# see logs with:
#   docker logs --follow <container_hash>
# stop and remove with:
#   docker stop <container_hash>