name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - 'README*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'WEEE-Open'

    steps:
    - uses: actions/checkout@v2

    - name: Login to our Docker registry
      uses: docker/login-action@v1
      with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build the run Docker image
      run: docker build . --file Dockerfile.run --build-arg PAT=${{ secrets.PAT }} --tag ${{secrets.DOCKER_REGISTRY}}/sardina:latest

    - name: Push the run Docker Image to our custom registry
      run: docker push ${{secrets.DOCKER_REGISTRY}}/sardina:latest
      
    - name: Build the cron Docker image
      run: docker build . --file Dockerfile.cron --tag ${{secrets.DOCKER_REGISTRY}}/sardina-cron:latest

    - name: Push the cron Docker Image to our custom registry
      run: docker push ${{secrets.DOCKER_REGISTRY}}/sardina-cron:latest
