name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - 'README*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'WEEE-Open'

    steps:
    - uses: actions/checkout@v2

    - name: Login to our Docker registry
      uses: docker/login-action@v1
      with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.run
        push: true
        tags: ${{secrets.DOCKER_REGISTRY}}/sardina:latest
